import {PhraseSet} from "wordgard/state"

/// The phrase set for the core packages. You can translate this to
/// internationalize the menus and dialogs created by those packages.
export const phrases = PhraseSet.define({
  dialog_close: "close",

  // Menu labels
  block_style: "Block style",
  toggle_strong: "Toggle strong emphasis",
  toggle_em: "Toggle emphasis",
  toggle_code: "Toggle code font",
  toggle_underline: "Toggle underline",
  toggle_super: "Toggle superscript",
  toggle_sub: "Toggle subscript",
  create_link: "Create a link",
  text_color: "Text color",
  undo: "Undo",
  redo: "Redo",
  paragraph: "Paragraph",
  code_block: "Code block",
  heading_1: "Heading 1",
  heading_2: "Heading 2",
  heading_3: "Heading 3",
  toggle_bullet_list: "Toggle bullet list",
  toggle_ordered_list: "Toggle ordered list",
  toggle_quote: "Toggle blockquote",
  alignment: "Alignment",
  align_start: "Align text to block start",
  align_end: "Align text to block end",
  align_center: "Center text",

  // Image interface
  insert_image: "Insert image",
  update_image: "Update image",
  update: "Update",
  insert: "Insert",
  cancel: "Cancel",
  inline: "Inline",
  figure: "Figure",
  figure_center: "Centered figure",
  figure_end: "Figure aligned to end",
  captioned: "Captioned",
  image_style: "Image style",
  uploading: "Uploading...",
  upload_failed: "Image upload failed",
  width: "Width in pixels",
  upload_image: "Upload an image",
  image_source: "Image source",
  alt_text: "Alternative text",
  describe_image: "Describe the image",

  // Table interface
  dimensions_title: "Table dimensions $1 by $2. Use arrow keys to change.",
  dimensions_live: "$1 by $2",
  insert_table: "Insert a table",
  modify_table: "Modify table",
  toggle_header: "Toggle header cells",
  add_row_above: "Add row above",
  add_row_below: "Add row below",
  delete_row: "Delete row",
  add_col_before: "Add column before",
  add_col_after: "Add column before",
  delete_col: "Delete column",
  merge_cells: "Merge cells",
  split_cell: "Split cell",

  // Color names FIXME maybe split off after all?
  col_none: "none",
  col_black: "black",
  col_white: "white",
  col_grey: "grey",
  col_red_berry: "red berry",
  col_red: "red",
  col_orange: "orange",
  col_yellow: "yellow",
  col_green: "green",
  col_cyan: "cyan",
  col_cornflower: "cornflower",
  col_blue: "blue",
  col_purple: "purple",
  col_magenta: "magenta",
  col_dark: "dark",
  col_darker: "darker",
  col_darkest: "very dark",
  col_light: "light",
  col_lighter: "lighter",
  col_lightest: "very light",
})
