name: Mirror upstream
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write
  actions: write

jobs:
  mirror-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - name: Merge
        id: merge
        run: |
          git config user.name ci
          git config user.email ci@nerd.bible
          git remote add upstream https://code.haverbeke.berlin/wordgard/wordgard.git
          git fetch upstream
          if git merge-base --is-ancestor upstream/main HEAD; then
            exit 1
          else
            git merge --no-edit upstream/main
            # prefer upstream tags
            if ! git describe --exact-match --tags HEAD;
              npx -p @nerd-bible/config gitBump beta
            fi
            git push --tags origin master
          fi
