name: Mirror upstream
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
permissions:
  contents: write
  actions: write

jobs:
  mirror-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - name: Merge
        id: merge
        run: |
          git config user.name ci
          git config user.email ci@nerd.bible
          git remote add upstream https://code.haverbeke.berlin/wordgard/wordgard.git
          git fetch upstream
          git merge --no-commit upstream/main
          if git diff | grep --quiet .; then
            git commit -m 'merge upstream/main'
            npx -p @nerd-bible/config gitBump
            git push --tags origin master
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          fi
      - uses: ./publish.yml
        if: steps.merge.deploy == 'true'
