name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"
      - run: npm install --force
      - run: npm test
      - run: npm run prepare
      - run: npx -p @nerd-bible/config pkgWrite
      - run: |
          TAG=$(echo $TAG_NAME | grep -oe '-.*$' | cut -c 2-)
          npm publish --verbose --access public --tag ${TAG:-latest}
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
